### ISSUE TITLE
Using python web scrapers present in Scrappers folder, automate codeclock.html (from static to dynamic webpage)

### ISSUE THREAD

**Issue by re4lvanshsingh** [re4lvanshsingh/Codeforces_Codechef_Converter#11]
Basically codeclock.html contains the date and time of upcoming contests on Codeforces, Atcoder, Codechef and Leetcode.

I want someone to automate this process:

The process: 
1) Fetch details of upcoming competitive programming contests from four websites - Codeforces, AtCoder, CodeChef and Leetcode.
(Already done and present in repo)

2) These details have been fetched using Codeforces API for Codeforces and Web Scrapers for AtCoder, CodeChef and Leetcode. (Already done and present in repo)

3) I want someone to edit codeclock.html and use JavaScript or some other backend to run the python webscrapers, fetch the details obtained from the python scripts and dynamically put it inside codeclock.html (previously these values were getting stored in csv file) and I have to manually put the data inside the div tag which is time consuming and static in nature.

This issue basically wants one to fix the 3) point. Basically just automate the process which was static earlier to dynamic. DONE!

**Comment by HavokSahil** [comment]
@re4lvanshsingh  assign this issue to me

**Comment by re4lvanshsingh** [comment]
@HavokSahil Assigned.

**Comment by HavokSahil** [comment]
@re4lvanshsingh  There is one issue the scrapers namely the leetcode in the scraper folder doesn't work properly.
