### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by re4lvanshsingh** [re4lvanshsingh/Codeforces_Codechef_Converter#12]
Just change README.md and include screenshots from the website explaining each and every feature.

Basically,
## Table of Contents
- [Introduction](#introduction)
- [Features](#features)
- [Installation](#installation)
- [Usage](#usage)
- [Documentation](#documentation)
- [Contributing](#contributing)
- [License](#license)

In Features I need screenshots of the working website and "concise" explanations.

**Comment by aindree-2005** [comment]
@re4lvanshsingh can I work on this?

**Comment by re4lvanshsingh** [comment]
@aindree-2005 Sure.

**Comment by aindree-2005** [comment]
@re4lvanshsingh what do I include

> Just change README.md and include screenshots from the website explaining each and every feature.
> 
> Basically,
> 
> ## Table of Contents
> * [Introduction](#introduction)
> * [Features](#features)
> * [Installation](#installation)
> * [Usage](#usage)
> * [Documentation](#documentation)
> * [Contributing](#contributing)
> * [License](#license)
> 
> In Features I need screenshots of the working website and "concise" explanations.

What do I include in the License and Documentation parts? @re4lvanshsingh

**Comment by re4lvanshsingh** [comment]
@aindree-2005 My repo got updated. Have you looked at the new home.html? Plus the old graph was a simple Polynomial Regression. Right now I have included a Hubor Regressor in the backend using JavaScript. Also take a look at the ipynb notebook made by HavokSahil. There you will find the further details of the project.

Please redo the features and also include the details of codeclock.html and its scrapers, home.html and the way R2 score was utlised over 20 ML Models using 5 features to determine the codechef rating from codeforces rating. Also, make sure to add your own comments over the work which you deem appropriate.

Also remove the entire talk about About My Model, Key Components and Project Overview. Rewrite them from scratch using above guidelines

**Comment by aindree-2005** [comment]
> @aindree-2005 My repo got updated. Have you looked at the new home.html? Plus the old graph was a simple Polynomial Regression. Right now I have included a Hubor Regressor in the backend using JavaScript. Also take a look at the ipynb notebook made by HavokSahil. There you will find the further details of the project.
> 
> Please redo the features and also include the details of codeclock.html and its scrapers, home.html and the way R2 score was utlised over 20 ML Models using 5 features to determine the codechef rating from codeforces rating. Also, make sure to add your own comments over the work which you deem appropriate.
> 
> Also remove the entire talk about About My Model, Key Components and Project Overview. Rewrite them from scratch using above guidelines

Oh let me check. I guess I forgot to sync fork

**Comment by aindree-2005** [comment]
@re4lvanshsingh updated the changes now!
