### ISSUE TITLE
Integrate Huber Regressor ML Model present in models_rating.ipynb in the Javascript of home.html to convert Codeforces to Codechef Rating

### ISSUE THREAD

**Issue by re4lvanshsingh** [re4lvanshsingh/Codeforces_Codechef_Converter#13]
To integrate a machine learning (ML) model into an HTML web page to predict values, you can follow these general steps:

1) Train and Export the Model:

Train your machine learning model using a suitable framework like TensorFlow or scikit-learn.
Once trained, export the model in a format that can be used in a web environment. Common formats include TensorFlow.js for TensorFlow models or a serialized format like pickle for scikit-learn models.

2) Create HTML Interface:

Design a simple HTML form that collects input data from the user. This form will be used to provide input for prediction.
Integrate JavaScript for Model Inference:

Use JavaScript to handle form submission and perform model inference. You can use TensorFlow.js if you're working with TensorFlow models or other JavaScript libraries for other frameworks.

Load the pre-trained model in the browser and use it to make predictions based on the user's input.

**Comment by HavokSahil** [comment]
@re4lvanshsingh  assign this issue to me

**Comment by re4lvanshsingh** [comment]
@HavokSahil Sure. Assigned.

**Comment by HavokSahil** [comment]
@re4lvanshsingh  I didn't found any way to load scikit learn model into javascript, it's available only for tensorflow. So I manually coded all the computation steps.

**Comment by re4lvanshsingh** [comment]
@HavokSahil Merged
