### ISSUE TITLE
Less number of points and features in the dataset

### ISSUE THREAD

**Issue by re4lvanshsingh** [re4lvanshsingh/Codeforces_Codechef_Converter#2]
In my dataset, I only have 57 points with only 1 feature i.e. rating.

I want to include more features like username, past 5 to 10 ratings, past 5 to 10 contest ranks, number of contests participated in and the number of accepted solutions (solved problems basically).

Also, I want more number of data points for higher rated users (Master+ on Codeforces and 6 stars+ on CodeChef). For this please use BeautifulSoup on Python or some other web-scraping technique to extract this data.

Prepare a csv file or excel file for the same. The number of data points should be atleast 300.

Make sure to take the data point only when the username is same on both the platforms. 
eg: if coder has the same username "braman" on both codeforces and codechef, only then take the data point.
If we take random isolated points of codeforces and codechef, then we can't really make the comparison.

**Comment by harshittomar0** [comment]
@re4lvanshsingh Assign this issue to me.

**Comment by re4lvanshsingh** [comment]
Sure. I just edited the issue a little bit. Take a look at it and go forward. Assigned.

**Comment by re4lvanshsingh** [comment]
@owl-Dr HavokSahil had already resolved the issue. Henceforth, closing it. I apologise if you have made efforts on this issue.
