### ISSUE TITLE
Add new webpage on navbar called "CodeClock"

### ISSUE THREAD

**Issue by re4lvanshsingh** [re4lvanshsingh/Codeforces_Codechef_Converter#4]
![website](https://github.com/re4lvanshsingh/Codeforces_Codechef_Converter/assets/95162817/2d906c34-f95a-4ef5-b26b-b8a29c35fda1)

Add a webpage called "CodeClock" on the navbar.

1) Clicking it, we reach a webpage which contains the four popular CP and DSA websites  upcoming contest timings- Codeforces, Codechef, Leetcode and AtCoder. 

2) I give full creative freedom for designing the website, just make the theme black and white like the original page.

3) Its pretty simple task with the use of each website's API. Incase the API isn't available inform me and for the time being, statically add the values to the HTML Page.

**Comment by aindree-2005** [comment]
@re4lvanshsingh I can work on adding the static web pages

**Comment by re4lvanshsingh** [comment]
@aindree-2005 Static pages are fine only if the relevant API for the website can't be implemented. Since codeforces API can be used to directly fetch the contest timings, I would like you to use a little bit of backend. Works for ya?

**Comment by aindree-2005** [comment]
@re4lvanshsingh Sure works for me! I haven't worked with apis much before though. So, if I get stuck somewhere I can contact you on the CodePeak server right?

**Comment by re4lvanshsingh** [comment]
Yeah sure! Free to help you out. A little bit of ChatGPT never hurt anybody too :)
Assigned

**Comment by re4lvanshsingh** [comment]
@aindree-2005 assigned

**Comment by aindree-2005** [comment]
> Yeah sure! Free to help you out. A little bit of ChatGPT never hurt anybody too :) Assigned

Thanks!
