### ISSUE TITLE
Convert the matplotlib obtained after training ML model to HTML using mpld3

### ISSUE THREAD

**Issue by re4lvanshsingh** [re4lvanshsingh/Codeforces_Codechef_Converter#5]
Just convert the matplotlib data obtained after using ML Model to a HTML script and then embed it into the webpage. Pretty simple.

NOTE: Make sure to complete the previous steps - Training the ML Model issue and Obtaining dataset issue before moving onto this issue.

**Comment by drockparashar** [comment]
Please assign this issue to me.

**Comment by re4lvanshsingh** [comment]
> Please assign this issue to me.

I could but what data would you use the matplotlib on? I need more data points in the original dataset.

**Comment by re4lvanshsingh** [comment]
@drockparashar

**Comment by drockparashar** [comment]
I will try to get some additional data on ratings.

**Comment by re4lvanshsingh** [comment]
Cool. I have assigned the issue

**Comment by HavokSahil** [comment]
@re4lvanshsingh Assign this issue to me.
But I need some clarification:
- Which plot is to be converted?
- In which html file is it to be embedded?
