### ISSUE TITLE
Add next 4 contests and their corresponding date and time for CodeChef, AtCoder and Leetcode using Web Scraping in codeclock.html

### ISSUE THREAD

**Issue by re4lvanshsingh** [re4lvanshsingh/Codeforces_Codechef_Converter#8]
Since there is no dedicated API for these platforms - CodeChef, AtCoder and LeetCode, I want someone to use Web-Scraping to fetch the contest data (next 4 contests, their date and timing) everytime I reload the page.

In more formal terms:
When you perform web scraping without an API, your script essentially simulates the process of a user accessing a webpage, fetching the HTML content, and extracting the relevant information. This means that every time you want the latest data, you would need to run your web scraping script to fetch the data from the website.

Use BeautifulSoup or some other WebScraper for this purpose. Now, add it to the HTML Page.

The query should be such that everytime I refresh the page, I am scraping the data from the original websites.

**Comment by GauravGupta993** [comment]
I would like to work on this issue. Please assign this issue to me.

**Comment by re4lvanshsingh** [comment]
@GauravGupta993 Sure, look at the previous work done in codeclock.html and begin. Incase of any query, DM me on discord or you could even ask it here.

Assigned.

**Comment by MiirzaBaig** [comment]
can i work on this?

**Comment by GauravGupta993** [comment]
> can i work on this?

I am already working on this issue.

**Comment by re4lvanshsingh** [comment]
@I-MirzaBaig You can work on this issue. @GauravGupta993 it has been 3 days since I assigned you the work. You should have completed this work earlier.

Whoever makes the PR first gets the point.

**Comment by GauravGupta993** [comment]
I am done with the Atcoder Scraping but the problem I am getting with Leetcode and CodeChef is that only the next 2 contests information are present on their sites instead of 4. https://www.codechef.com/contests/  https://leetcode.com/contest/

**Comment by re4lvanshsingh** [comment]
@GauravGupta993 No problem. 

When you scrape the websites, only two tuples would appear instead of the usual 4. Ignore the NULL values and then display only those two values.
